# -*- coding: utf-8 -*-
"""agentic RAG system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cuEP_-PtZrfWvbWKFrZa3YJPFhC0bBFY
"""

!pip install sentence-transformers faiss-cpu pandas scikit-learn rouge-score

import os
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer
import faiss
from sklearn.metrics.pairwise import cosine_similarity
from rouge_score import rouge_scorer

from google.colab import files

uploaded = files.upload()

docs = []

for file in uploaded:
    content = uploaded[file].decode("utf-8")
    docs.append(content)

print(f"Loaded {len(docs)} documents")

print(docs[0][:500])

def chunk_text(text, chunk_size=300, overlap=50):
    words = text.split()
    chunks = []

    for i in range(0, len(words), chunk_size - overlap):
        chunk = " ".join(words[i:i + chunk_size])
        chunks.append(chunk)

    return chunks

all_chunks = []
for doc in docs:
    all_chunks.extend(chunk_text(doc))

print("Total chunks:", len(all_chunks))

!pip install sentence-transformers faiss-cpu

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

model = SentenceTransformer('all-MiniLM-L6-v2')

embeddings = model.encode(all_chunks)

dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(np.array(embeddings))

print("FAISS index ready")

def classify_query(query):
    query = query.lower()

    if any(word in query for word in ["compare", "difference", "impact", "analyze"]):
        return "synthesis"

    elif any(word in query for word in ["what", "who", "when", "where", "define"]):
        return "factual"

    else:
        return "out_of_scope"

def retrieve(query, k=3):
    query_embedding = model.encode([query])
    distances, indices = index.search(np.array(query_embedding), k)

    return [all_chunks[i] for i in indices[0]]

def generate_answer(query, query_type):

    if query_type == "out_of_scope":
        return "The information is not available in the provided documents."

    chunks = retrieve(query)
    return " ".join(chunks)

def ask(query):
    q_type = classify_query(query)
    answer = generate_answer(query, q_type)

    print("Query Type:", q_type)
    print("Answer:", answer[:300])

ask("What is AI regulation?")
ask("Compare AI laws in different countries")
ask("Who is Elon Musk?")

test_data = [
    {"query": "What is AI regulation?", "type": "factual", "expected": "AI regulation refers to laws and policies governing artificial intelligence."},
    {"query": "Define AI ethics", "type": "factual", "expected": "AI ethics deals with moral principles guiding AI systems."},
    {"query": "What is GDPR?", "type": "factual", "expected": "GDPR is a data protection regulation in the EU."},
    {"query": "Who regulates AI systems?", "type": "factual", "expected": "Governments and regulatory bodies oversee AI."},
    {"query": "What are AI risks?", "type": "factual", "expected": "AI risks include bias, privacy issues, and misuse."},


    {"query": "Compare AI regulations across countries", "type": "synthesis", "expected": "Different countries have varying AI policies and frameworks."},
    {"query": "Impact of AI laws on companies", "type": "synthesis", "expected": "Companies must comply with regulations affecting innovation and cost."},
    {"query": "Analyze AI risk frameworks", "type": "synthesis", "expected": "Risk frameworks classify AI based on potential harm."},
    {"query": "Difference between US and EU AI laws", "type": "synthesis", "expected": "EU has stricter AI laws than the US."},
    {"query": "How AI regulation affects innovation", "type": "synthesis", "expected": "Regulation can both slow and guide innovation."},


    {"query": "Who is Elon Musk?", "type": "out_of_scope", "expected": "not available"},
    {"query": "Weather today?", "type": "out_of_scope", "expected": "not available"},
    {"query": "Best programming language?", "type": "out_of_scope", "expected": "not available"},
    {"query": "Stock price of Tesla?", "type": "out_of_scope", "expected": "not available"},
    {"query": "Who won IPL 2025?", "type": "out_of_scope", "expected": "not available"}
]

!pip install rouge-score

from rouge_score import rouge_scorer
import pandas as pd

scorer = rouge_scorer.RougeScorer(['rouge1'], use_stemmer=True)

results = []

for item in test_data:
    output = ask(item["query"])

    predicted_type = classify_query(item["query"])
    expected_type = item["type"]

    predicted_answer = generate_answer(item["query"], predicted_type)
    expected_answer = item["expected"]

    # ROUGE score
    rouge = scorer.score(expected_answer, predicted_answer)['rouge1'].fmeasure

    results.append({
        "query": item["query"],
        "expected_type": expected_type,
        "predicted_type": predicted_type,
        "rouge_score": round(rouge, 3)
    })

df = pd.DataFrame(results)
df

df.to_csv("results.csv", index=False)

routing_accuracy = (df["expected_type"] == df["predicted_type"]).mean()
print("Routing Accuracy:", routing_accuracy)

